language: python
python:
- '2.7'
- '3.4'
cache:
- pip
install:
- pip install -r requirements.txt
script:
- python cro/tests.py
deploy:
    provider: pypi
    user: victorpelaez
      password:
        secure: ljG9nLZRspQ+aDjugmIG0uw2ea9tVDCvjHJbD05GQc99gbfgS+Ontl3C7rY6pGgm+r57PJeYkmOecjXlWigkbYTxAN0KjDZzZaR5STdRPBnMJjd0kDmxIWdk8efley3B5qZH2+AG9GIPjOJMVUwlgr89eJ/2pqXqWUtf1C5hFp018HUK0iTyVNlGwv9E3MeVmH8KP3niqzP9ZED5Fd9x7Oe1yDxudLiatB7geRLgt0nOm3d4of1qn+lQpwPFtQgEqfS5i8XoCTmRssvoaV44hpmg+QxwvSR+Ku3Hw505X5rXc5tns22wk0NgAmyZzYspKjieueL0aELRJ7XFF9Gfj51X8WKywjWSRu6wpz6qwjw25PSRMIT4NiQ/aW3dWV7Xi6vNFj9FurEzzQl5OLFxH1dvZx/OCtGyJgAhFp4UbWNTFhM4Xu/U5KdCAI5vSDQWW9WYA+C23In+LV8ESvLJfyJmC+cl1UQIB02VFyZE9b+OgcaUg7+4KFNbcLUMvzuza/EO4FNVWTkyUGtNE7R6VAdX6MmLTC16MNnFCp3LLIiXgcNGqsyQpdbckzf63MAg+PLGKjqhxJzUsPaxkon5dUT4tahESXbVBuo+mudHEtJS0rRu8ViXTz+u3nAHmSOxwr4sTh/vlCgsPMWfZfmHn1ql8TjXszrbe13wMUq8Ecw=
    distributions: sdist bdist_wheel
    on:
      branch: master

