language: python
python:
- '2.7'
- '3.4'
cache:
- pip
install:
- pip install -r requirements.txt
script:
- pytest cro/tests/
deploy:
  provider: pypi
  user: victorpelaez
  password:
    secure: Qj3yst21NLpYykQBCrMXLcB1ESHEDx5f0vxxjqv5PCBpBgFKPBdEurl2gTA0yiun9VAaL0Qc/bfg+P31rditLqLXjPHUOySV8TWH2kzmITQOCM7eciHjPoQsy94r75bGP0b8Mel7J2cR5ygh88jZQP+P9dKjPQnqqIvEZnEeHMu3URPMfrY+wRUn3Sgn0SaX98Zll33EiOuWhdOL7kNWfj149uLaB1ZGfeGacj7gIeQyp/lotad3f8pkCgSCYFFlV16kUZ3DLG7poc9o3V8X4r69sPCypDZqAVsRTDmoW7/06xz32v+5hsyVTN7k9Emgz+ISOy0I33go9y5eJauvysrgaeSdkHuPaZoR3+2ymsxaXmVy0Y7QekrnCh208fVK9yGQjW0UJ0oP2tNGgr7Lg/Y6p47ZAXt/9fLLxKRa/PCkHDlhDTyQXiNzBtzmZtbg69z0cv+sf6J5PDCs9pbhuk0dVoPnsfxexcHKjB/sFWWuZ+UDFpXzNKU26OnLIm/I8gazmOh53Kr6cAx6i0zAPaYGn3Dq2bdZ+A2K4iRg+mlSW1mEx3vuA0Q/5RH45RERIUj+ZATqtAx0fKJcBtJHoFvJRuuNeky/8au4nvSLOt7He5FYfTsx+Da5IsN01ksvd13Xa8aocSyFAgPgnWcn5hRidPkiqBHEaLBPfuMo01I=
  on:
    distributions: sdist bdist_wheel
    branch: master
